### ISSUE TITLE
Update doc-userstories.md to USER_STORIES.md #19

### ISSUE THREAD

**Issue by arthurmdros** [ZauJulio/Taskiano#19]
Criei um arquivo chamado USER_STORIES.md, e organize os User Stories. Um User Story combinam um ou mais requisitos funcionais necessários para a execução da estória do usuário. Deve ser detalhado pelo menos 1 User Story por membro da equipe. Utilize o modelo de ficha de user story definido no Processo de Desenvolvimento do BSI. Coloque ele no diretório docs/ e um link no README.

**Comment by arthurmdros** [comment]
Em cada ficha de USER STORY, deve ser descritos os Testes de Aceitação. Os testes devem está bem detalhados e com casos de testes positivos e negativos. Aloque pelo menos um User Story por membro da equipe, não precisa ser o mesmo membro da equipe que fez o detalhamento do User Story, mas cada membro deve fazer.

**Comment by linhox** [comment]
Pequenas alterações necessárias no doc para corrigir características que foram mudadas.
